# Generated by Django 5.0.6 on 2024-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
